server:
  port: ${ucloudteach.pay.port}
# dubbo 配置
dubbo:
  application:
    name: ucloudteach-pay-service
  registry:
    protocol: ${ucloudteach.dubbo.registry.protocol}
    address: ${ucloudteach.dubbo.registry.address}
  protocol:
    name: ${ucloudteach.pay.dubbo.protocol.name}
    port: ${ucloudteach.pay.dubbo.protocol.port}
  monitor:
    protocol: registry
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/ucloud?useSSL=false&allowMultiQueries=true
    username: test
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
