spring:
  application:
    name: ucloudteach-async-service
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: zebinmail@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: OZHCBGDPUXWIBUGC
    # 端口号465
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  # 消息队列配置
  rabbitmq:
    host: 101.33.204.207
    username: oliver
    password: MQlzb2020.
    # 设置该属性后可以限定一次接受的消息数量 待手动确认后再次收取【消费端消峰】
    listener:
      simple:
        prefetch: 2
    port: 5672
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

